name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install XTP CLI
        run: curl https://static.dylibso.com/cli/install.sh | bash

      - name: Check XTP CLI version
        run: xtp -v

      - name: Install Extism js-pdk
        run: |
          curl -Ls https://raw.githubusercontent.com/extism/js-pdk/main/install.sh | bash

      - name: Check
        run: |
          npm i
          npm run check

      - name: Build example
        run: cd examples/basic && npm i && npm run build

      - name: Test example
        run: |
          # this is configured with the xtp.toml file in the root
          xtp plugin test
      
