name: 'Publish to npm'

on: 
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Build @dylibso/xtp-test
        run: |
          make build-npm tag=${{ github.ref_name }}
        
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Publish @dylibso/xtp-test
        run: |
          cd npm
          npm ci
          npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
          CI: true
        
      
